name: Auto-build & release to test-builds repo
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm

    needs: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: oudedetai-${{ matrix.arch }}-${{ github.run_id }}

    - name: Make binary executable
      run: chmod +x oudedetai-${{ matrix.arch }}-${{ github.run_id }}

    - name: Upload release to test repo
      uses: softprops/action-gh-release@v1
      with:
        tag_name: main-latest
        prerelease: true
        files: oudedetai-${{ matrix.arch }}-${{ github.run_id }}
        repository: FaithLife-Community/test-builds
        token: ${{ secrets.N8MARTI_ACCESS_TOKEN }}
        
