name: Build & release to test-builds repo
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch to build"
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: ${{ inputs.branch }}

  release:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
        arch: [x86_64, arm]
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: oudedetai-${{ matrix.arch }}

    - name: Fix file permissions
      run: chmod +x oudedetai-${{ matrix.arch }}

    - name: Upload release to test repo
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.branch }}-${{ needs.build.outputs.sha_short }}
        prerelease: true
        files: oudedetai-${{ matrix.arch }}
        repository: FaithLife-Community/test-builds
        token: ${{ secrets.N8MARTI_ACCESS_TOKEN }}
