name: Build & release

on:
  #schedule:
  #  - cron: '0 4,16 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: "The version string (e.g. 'v4.0.0-alpha.1'):"
        required: true
        type: string
      prerelease:
        description: "Check if pre-release"
        required: true
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: oudedetai-${{ matrix.arch }}

    - name: Make binary executable
      run: chmod +x oudedetai-${{ matrix.arch }}

    - name: Upload release to GitHub
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag }}
        draft: true
        prerelease: ${{ inputs.prerelease }}
        files: oudedetai-${{ matrix.arch }}
