name: Build branch with PyInstaller
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      bin_name_x86_64:
        description: "name of x86_64 built binary"
        value: ${{ jobs.build.outputs.bin_name_x86_64 }}
      bin_name_arm:
        description: "name of ARM built binary"
        value: ${{ jobs.build.outputs.bin_name_arm }}
      sha:
        value: ${{ github.sha }}
      sha_short:
        description: "1st few chars of commit SHA"
        value: ${{ jobs.build.outputs.sha_short }}
  workflow_dispatch:
    inputs:
      branch:
        description: "branch to build from:"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
        arch: [x86_64, arm]
    outputs:
      bin_name_x86_64: ${{ steps.pyinstaller.outputs.bin_name_x86_64 }}
      bin_name_arm: ${{ steps.pyinstaller.outputs.bin_name_arm }}
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Get 1st 7 chars of commit SHA
      id: sha
      run: |
        sha="$(git log -n 1 ${{ inputs.branch }} | grep commit | awk '{print $2}')"
        echo $sha
        echo "sha_short=${sha:0:7}" >> $GITHUB_OUTPUT

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: pip

    - name: Install dependencies
      run: |
        # apt-get install python3-tk
        pip install --upgrade pip
        pip install .[build]

    - name: Build with pyinstaller
      id: pyinstaller
      run: |
        ARCH=${{ matrix.arch }}
        BIN_NAME="oudedetai-${ARCH}-${{ github.run_id }}"
        ./scripts/build-binary.sh $ARCH
        mv dist/oudedetai "dist/$BIN_NAME"
        
        # Ensure both outputs are always set, avoiding null issues
        if [[ "$ARCH" == "x86_64" ]]; then
          echo "bin_name_x86_64=$BIN_NAME" >> $GITHUB_OUTPUT
          echo "bin_name_arm=" >> $GITHUB_OUTPUT  # Ensure this output exists
        else
          echo "bin_name_arm=$BIN_NAME" >> $GITHUB_OUTPUT
          echo "bin_name_x86_64=" >> $GITHUB_OUTPUT  # Ensure this output exists
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.pyinstaller.outputs.bin_name_x86_64 || steps.pyinstaller.outputs.bin_name_arm }}
        path: dist/${{ steps.pyinstaller.outputs.bin_name_x86_64 || steps.pyinstaller.outputs.bin_name_arm }}
        compression-level: 0